name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # MSRV and nightly
        version: [1.61.0, stable, nightly]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set toolchain
        run: |
          rustup set profile minimal
          rustup override set ${{ matrix.version }}

      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7

      - name: Rustfmt check
        if: matrix.version == '1.61.0'
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check

      - name: Run `cargo test` on workspace
        if: matrix.version != '1.61.0'
        run: cargo test --workspace --exclude=phf_codegen_test

      - name: phf_codegen test
        if: matrix.version != '1.61.0'
        run: cargo test -p phf_codegen_test

      - name: no_std build check
        working-directory: phf
        run: cargo build --no-default-features

      - name: unicase + macros features check
        run: cargo check -p unicase-example
